### ISSUE TITLE
Error messages in Terminal [BUG]

### ISSUE THREAD

**Issue by blue492** [tneotia/html-editor-enhanced#11]
I implemented html-editor-enhanced in a separate class as you see

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'dart:async';
import 'dart:core';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:html_editor_enhanced/html_editor.dart';
import 'dart:convert';
import 'dart:io';


class html_textbox extends StatefulWidget {
  String value;
  html_textbox(this.value);

  @override
  _html_textboxState createState() => _html_textboxState();
}

class _html_textboxState extends State<html_textbox> {
  final HtmlEditorController controller = HtmlEditorController();

  @override
  void initState() {

    super.initState();

  }

  @override
  void dispose() {
    super.dispose();

  }




   return_back_html_text(BuildContext context) async{
     final result = await controller.getText();

      Navigator.pop(context, result);
   
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(

        title: Text('Change text', textScaleFactor: 1,),
        actions: [
          TextButton(onPressed: () async{

            return_back_html_text(context);

          }, child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Icon(Icons.check, color: Colors.white, size: 25,),
              Text(' Save', textScaleFactor:  1.2, style: TextStyle(color: Colors.white),),
            ],
          )),
        ],
      ),

      body:   SingleChildScrollView(
    child: Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: <Widget>[
          HtmlEditor(
            controller: controller,
            hint: "Skriv här...",
            initialText:  widget.value,

            options: HtmlEditorOptions(
            height: 400,
              showBottomToolbar: false,
              autoAdjustHeight: false,
              adjustHeightForKeyboard: false,
              shouldEnsureVisible: true
            ),

            toolbar: [
             Style(),
              Font(buttons: [FontButtons.bold,  FontButtons.italic, FontButtons.clear, FontButtons.underline],),
            ],

     
          /*  callbacks: Callbacks(
              onChange: (String changed) {
                //  value = changed;
                print("content changed to $changed");
              },
              onEnter: () {
                print("enter/return pressed");
              },
              onFocus: () {
                print("editor focused");
              },
              onBlur: () {
                print("editor unfocused");
              },
              onBlurCodeview: () {
                print("codeview either focused or unfocused");
              },
              onInit: () {
                print("init");
              },
              onKeyDown: (int keyCode) {
                print("$keyCode key downed");
              },
              onKeyUp: (int keyCode) {
                print("$keyCode key released");
              },
              onPaste: () {
                print("pasted into editor");
              },
            ),*/

          ),


          Container(
            margin: EdgeInsets.only(left: 15, right: 15),
            child: OutlineButton(
                onPressed: () async{

              await return_back_html_text(context);

            }, child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Icon(Icons.check, color: Colors.green, size: 25,),
                Text(' Save', textScaleFactor:  1.2, style: TextStyle(color: Colors.green),),
              ],
            ),
              shape: new RoundedRectangleBorder(
                  borderRadius: new BorderRadius.circular(30.0)),
              borderSide: BorderSide(
                color: Colors.green, //Color of the border
                style: BorderStyle.solid, //Style of the border
                width: 1.0, //width of the border
              ),),
          ),
        ],
      ),
      ),
    );
  }
}
```

The problem I do Navigator.push to this page, I could open the page but it shows the following error messages in terminal
```
E/flutter (14486): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'double' is not a subtype of type 'int?' in type cast
E/flutter (14486): #0      _HtmlEditorWidgetMobileState.build.<anonymous closure> (package:html_editor_enhanced/src/widgets/html_editor_widget_mobile.dart:303:57)
E/flutter (14486): #1      _HtmlEditorWidgetMobileState.build.<anonymous closure> (package:html_editor_enhanced/src/widgets/html_editor_widget_mobile.dart:168:23)
E/flutter (14486): #2      InAppWebViewController.handleMethod (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:123:34)
E/flutter (14486): #3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:435:55)
E/flutter (14486): #4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:382:34)
E/flutter (14486): #5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284:33)
E/flutter (14486): #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:221:15)
E/flutter (14486): #7      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (14486): #8      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14486): #9      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14486): #10     _invoke3 (dart:ui/hooks.dart:220:10)
E/flutter (14486): #11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:457:7)
E/flutter (14486): #12     _dispatchPlatformMessage (dart:ui/hooks.dart:90:31)
E/flutter (14486): 

```

When I click on Save button, it works I got the text I wrote correctly, but it shows  the following error messages in terminal
```
E/chromium(14486): [ERROR:aw_browser_terminator.cc(125)] Renderer process (19914) crash detected (code -1).
E/flutter (14486): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter (14486): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
E/flutter (14486): #1      _HtmlEditorWidgetMobileState.build.<anonymous closure> (package:html_editor_enhanced/src/widgets/html_editor_widget_mobile.dart:100:23)
E/flutter (14486): #2      _HtmlEditorWidgetMobileState.build.<anonymous closure> (package:html_editor_enhanced/src/widgets/html_editor_widget_mobile.dart:99:28)
E/flutter (14486): #3      VisibilityDetectorLayer._fireCallback (package:visibility_detector/src/visibility_detector_layer.dart:261:24)
E/flutter (14486): #4      VisibilityDetectorLayer._processCallbacks (package:visibility_detector/src/visibility_detector_layer.dart:220:15)
E/flutter (14486): #5      _TaskEntry.run.<anonymous closure> (package:flutter/src/scheduler/binding.dart:80:34)
E/flutter (14486): #6      Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (14486): #7      _TaskEntry.run (package:flutter/src/scheduler/binding.dart:77:16)
E/flutter (14486): #8      SchedulerBinding.handleEventLoopCallback (package:flutter/src/scheduler/binding.dart:460:15)
E/flutter (14486): #9      SchedulerBinding._runTasks (package:flutter/src/scheduler/binding.dart:438:9)
E/flutter (14486): #10     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (14486): #11     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14486): #12     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14486): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14486): #14     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (14486): #15     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14486): #16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter (14486): #17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (14486): #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (14486): #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (14486): #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (14486): 

```

What is the problem?
Another issuse is sometimes it shows the default toolbar  even if you specified which buttons I want to show, 

Thanks for your good work.

**Comment by tneotia** [comment]
For the first error in terminal, that was fixed (see #6). It is not released on Pub yet, only master. I will be releasing shortly as 1.7.0+1.

For the second one, that is indeed an issue, not a breaking one as the `Stream` just handles the automatic height, but still I will fix it, probably I will include it in the above release.

**Comment by blue492** [comment]
@tneotia  You are doing a great job, thanks

**Comment by tneotia** [comment]
I didn't notice the last issue, you said it is showing the default toolbar sometimes? That should not be possible because it directly creates the `String` for the toolbar and then initializes the editor with it. If you have a way to reproduce this let me know so I can figure out why this is the case.

**Comment by tneotia** [comment]
@blue492 1.7.0+1 is now available on Pub, hopefully this fixes your first two issues.

**Comment by blue492** [comment]
> @blue492 1.7.0+1 is now available on Pub, hopefully this fixes your first two issues.

Yes the first two issues are fixed now, Thanks
