### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by arbazKnarkz** [tneotia/html-editor-enhanced#111]
**Describe the bug**
html_editor_enhanced: ^2.2.0
shortcuts.dart

```
Line 359:      final BuildContext primaryContext = primaryFocus!.context!;
======== Exception caught by services library ======================================================
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:359:64)
#1      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:708:20)
#2      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1678:43)
#3      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:682:69)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
...
====================================================================================================
```

**To Reproduce**
1. Insert some HTML text
2. Then try to add some text from keyboard
3. try to insert space from keyboard

**Device:**
IOS emulator 14.5

**Comment by tneotia** [comment]
This looks like an internal Flutter error rather than from the plugin itself
