### ISSUE TITLE
DOMException [BUG]

### ISSUE THREAD

**Issue by husamhamu12** [tneotia/html-editor-enhanced#120]
**Describe the bug**
I am getting this error a lot on flutter web.  

`TypeError: Cannot read property 'setAttribute' of undefined
    at handleMessage (about:srcdoc:64:68)
DOMException: Failed to execute 'setStart' on 'Range': The offset 5 is larger than the node's length (1).
    at t.value (http://localhost:/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js:2:24950)
    at t.value (http://localhost:/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js:2:29853)
    at t.value (http://localhost:/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js:2:80888)
    at t.value (http://localhost:/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js:2:81569)
    at HTMLDivElement.summernote.keyup (http://localhost:52648/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js:2:80592)
    at HTMLDivElement.dispatch (http://localhost:/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:43090)
    at HTMLDivElement.v.handle (http://localhost:/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:41074)
    at Object.trigger (http://localhost:/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:71513)
    at HTMLDivElement.<anonymous> (http://localhost:/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:72108)
    at Function.each (http://localhost:52648/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:2976)
`

**To Reproduce**
1. Type something 
2. Click on any button related to the font 
3. click to type again 

**Screenshots**
getting an error when trying to type something like this:
![image](https://user-images.githubusercontent.com/88487403/130795703-13152838-bfad-4728-99e8-327bf40b848e.png)

**Device:**
chrome (web)

**Additional context**
Honestly, it seems like nothing working as expected. For example, I am also getting errors when trying to upload an image too. But that is for another issue.

**Comment by tneotia** [comment]
What version of the package are you using? This is the first time I've seen those errors but it is working for everyone else on Web. The Type error shouldn't matter too much, don't worry about that one.

**Comment by husamhamu12** [comment]
After wrapping the scaffold with GestureDetector (I saw this in your implementation) the errors gone. But I still can't upload an image. I guess I will report this later. Thanks though.

**Comment by tneotia** [comment]
> But I still can't upload an image.

Sure whenever you get a chance please let me know what errors you are getting.

> I think it is related to the focus of the editor.

Quite possible, though I can't control it because it is from a library (summernote) that I use.
