### ISSUE TITLE
[BUG] Can't click on HTML editor in release APK on my mobile.

### ISSUE THREAD

**Issue by abhinavmarwaha** [tneotia/html-editor-enhanced#154]
**Describe the bug**
I can't click on HTML editor in release APK on my mobile. (while it works on my emulator)

**Source Code**
```
import 'package:flutter/material.dart';
import 'package:html_editor_enhanced/html_editor.dart';
import 'package:latlong2/latlong.dart';
import 'package:lifehq/journal/models/journal_entry.dart';
import 'package:lifehq/journal/services/journal_service.dart';
import 'package:lifehq/location/picker.dart';
import 'package:lifehq/skeleton.dart';
import 'package:lifehq/utils/utils.dart';
import 'package:osm_nominatim/osm_nominatim.dart';
import 'package:provider/provider.dart';

class JournalEntryInput extends StatefulWidget {
  const JournalEntryInput({Key? key}) : super(key: key);

  static const routeName = '/add-entry';

  @override
  _JournalEntryInputState createState() => _JournalEntryInputState();
}

class _JournalEntryInputState extends State<JournalEntryInput> {
  HtmlEditorController controller = HtmlEditorController();

  // String _bodytext = "";
  String title = "";
  Map? _pickedLocation = {};
  String _displayLocationName = "";
  List<String> selectedTags = [];

  DateTime _dateTime = DateTime.now();
  DateTime selectedDate = DateTime.now();
  TimeOfDay selectedTime = TimeOfDay(hour: 00, minute: 00);

  Future<Null> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
        context: context,
        initialDate: selectedDate,
        firstDate: DateTime(2019, 1),
        lastDate: DateTime(2111));
    if (picked != null)
      setState(() {
        selectedDate = picked;
        _dateTime = DateTime(selectedDate.year, selectedDate.month,
            selectedDate.day, _dateTime.hour, _dateTime.minute);
      });
  }

  Future<Null> _selectTime(BuildContext context) async {
    final TimeOfDay? picked = await showTimePicker(
      context: context,
      initialTime: selectedTime,
    );
    if (picked != null)
      setState(() {
        selectedTime = picked;
        _dateTime = DateTime(_dateTime.year, _dateTime.month, _dateTime.day,
            selectedTime.hour, selectedTime.minute);
      });
  }

  Future getLocation() async {
    Utilities.showInfoToast("Don't forget to on the GPS!");

    Map? result = await showDialog(
        context: context,
        builder: (BuildContext ctx) {
          return NominatimLocationPicker(
            searchHint: 'Location',
            awaitingForLocation: "Awaiting Location",
          );
        });
    if (result != null) {
      LatLng latLng = result["latlng"];

      final reverseSearchResult = await Nominatim.reverseSearch(
        lat: latLng.latitude,
        lon: latLng.longitude,
        addressDetails: true,
        extraTags: true,
        nameDetails: true,
      );
      setState(() {
        _pickedLocation = result;
        _displayLocationName = reverseSearchResult.displayName;
      });
    } else {
      return;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Skeleton(
        child: Consumer<JournalService>(
            builder: (context, journalService, child) => SafeArea(
                    child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        GestureDetector(
                          onTap: () {
                            getLocation();
                          },
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Icon(Icons.navigation),
                          ),
                        ),
                        _pickedLocation != null
                            ? Expanded(
                                child: SizedBox(
                                  height: 20,
                                  child: Text(
                                    _displayLocationName,
                                    maxLines: 1,
                                    overflow: TextOverflow.ellipsis,
                                  ),
                                ),
                              )
                            : Container(),
                        GestureDetector(
                            onTap: () {
                              Navigator.pop(context);
                            },
                            child: Icon(Icons.cancel)),
                      ],
                    ),
                    if (journalService.tags.length != 0)
                      SizedBox(
                        height: 48,
                        child: ListView.builder(
                          itemBuilder: (context, index) {
                            return GestureDetector(
                                onTap: () {
                                  setState(() {
                                    if (selectedTags
                                        .contains(journalService.tags[index]))
                                      selectedTags
                                          .remove(journalService.tags[index]);
                                    else
                                      selectedTags
                                          .add(journalService.tags[index]);
                                  });
                                },
                                child: Padding(
                                  padding: const EdgeInsets.all(8.0),
                                  child: Container(
                                    decoration: BoxDecoration(
                                        borderRadius: BorderRadius.circular(15),
                                        border: Border.all(
                                            color: selectedTags.contains(
                                                    journalService.tags[index])
                                                ? Colors.white
                                                : Colors.grey)),
                                    child: Padding(
                                      padding: const EdgeInsets.all(4.0),
                                      child: Center(
                                        child: Text(
                                          journalService.tags[index],
                                          style: TextStyle(
                                              fontSize: 12,
                                              color: selectedTags.contains(
                                                      journalService
                                                          .tags[index])
                                                  ? Colors.white
                                                  : Colors.grey),
                                        ),
                                      ),
                                    ),
                                  ),
                                ));
                          },
                          itemCount: journalService.tags.length,
                          scrollDirection: Axis.horizontal,
                        ),
                      ),
                    SizedBox(
                      height: 4,
                    ),
                    Row(children: [
                      Spacer(),
                      GestureDetector(
                          onTap: () => _selectDate(context),
                          child: Text(Utilities.beautifulDate(_dateTime)
                              .split("at")[0])),
                      Text(" at "),
                      GestureDetector(
                          onTap: () => _selectTime(context),
                          child: Text(Utilities.beautifulDate(_dateTime)
                              .split("at")[1]))
                    ]),
                    SizedBox(
                      height: 4,
                    ),
                    Row(
                      children: [
                        Expanded(
                          child: TextFormField(
                            onChanged: (value) => title = value,
                            cursorColor: Colors.white,
                            style: TextStyle(fontSize: 24),
                            decoration: InputDecoration(
                                border: InputBorder.none,
                                errorBorder: InputBorder.none,
                                enabledBorder: InputBorder.none,
                                focusedBorder: InputBorder.none,
                                disabledBorder: InputBorder.none,
                                focusedErrorBorder: InputBorder.none,
                                hintText: "Title"),
                          ),
                        ),
                        GestureDetector(
                            onTap: () async {
                              Provider.of<JournalService>(context,
                                      listen: false)
                                  .saveJournalEntry(JournalEntry(
                                      date: _dateTime,
                                      tags: selectedTags,
                                      lastModified: DateTime.now(),
                                      latitude:
                                          _pickedLocation!["latlng"]?.latitude,
                                      longitude:
                                          _pickedLocation!["latlng"]?.longitude,
                                      locationDisplayName: _displayLocationName,
                                      text: await controller.getText(),
                                      title: title))
                                  .then((value) => Navigator.pop(context));
                            },
                            child: Icon(Icons.arrow_forward_ios))
                      ],
                    ),
                    SizedBox(
                      height: 12,
                    ),
                    // TODO HTML EDITOR NOT WORKING.
                    Expanded(
                      child: HtmlEditor(
                          callbacks: Callbacks(
                              onInit: () => controller.setFullScreen()),
                          controller: controller,
                          htmlEditorOptions: HtmlEditorOptions(
                              darkMode: true,
                              hint: "body",
                              inputType: HtmlInputType.text,
                              shouldEnsureVisible: true,
                              adjustHeightForKeyboard: true,
                              autoAdjustHeight: true),
                          htmlToolbarOptions: HtmlToolbarOptions(
                              toolbarPosition: ToolbarPosition.belowEditor,
                              defaultToolbarButtons: const [
                                StyleButtons(),
                                FontSettingButtons(fontSizeUnit: false),
                                FontButtons(clearAll: false),
                                ColorButtons(),
                                ListButtons(listStyles: false),
                                ParagraphButtons(
                                    textDirection: false,
                                    lineHeight: false,
                                    caseConverter: false),
                                InsertButtons(
                                    video: true,
                                    audio: true,
                                    table: true,
                                    hr: true,
                                    otherFile: true)
                              ])),
                    )
                  ],
                ))));
  }
}

```
**Expected behavior**
I should be able to atleast click the editor?

**Device:**
Poco F1
Lineage OS 17.1

**Additional context**
When there is a call to `controller.getText()`  I get this error in logcat:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: HTML editor is still loading, please wait before evaluating this JS: $('#summernote-2').summernote('code');!
#0      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:262)
#1      HtmlEditorController.getText (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:70)
#2      _JournalEntryInputState.build.<anonymous closure>.<anonymous closure> (package:lifehq/journal/journal_entry_input.dart:226)
#3      _JournalEntryInputState.build.<anonymous closure>.<anonymous closure> (package:lifehq/journal/journal_entry_input.dart:214)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279)
#21     _rootRunUnary (dart:async/zone.dart:1444)
#22     _CustomZone.runUnary (dart:async/zone.dart:1335)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#24     _invoke1 (dart:ui/hooks.dart:185)
#25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:98)
```

**Comment by liaoxuewei** [comment]
> Can you check if you are able to click on webview page using `flutter_inappwebview` package on your mobile? Seems like the webview is not being loaded for some reason.

If the UI display is normal, but the editor cannot be activated and entered, it indicates that the fluent_ Is inappwebview normal?

**Comment by tneotia** [comment]
Hi, could you send a picture or screen recording for what you see?

**Comment by liaoxuewei** [comment]
The code come from https://pub.flutter-io.cn/packages/html_editor_enhanced/example

![image](https://user-images.githubusercontent.com/970765/146624825-beea1fbc-2693-4d74-941e-b50c3694bb0d.png)

**Comment by liaoxuewei** [comment]
I'm not sure if my mobile using flutter_inappwebview package, and then I don't know how to determine.

**Comment by liaoxuewei** [comment]
Any ideas? What is the key to solving the problem? Thanks! @tneotia

**Comment by liaoxuewei** [comment]
> Did you try and add internet permission to Android manifest? `<uses-permission android:name="android.permission.INTERNET"/>`

Is this necessary?

**Comment by liaoxuewei** [comment]
I see that I don't have this permission at present.

**Comment by liaoxuewei** [comment]
I'll try adding permissions.

**Comment by liaoxuewei** [comment]
It looks ok. Thank you very much!@tneotia

**Comment by liaoxuewei** [comment]
In addition, it is convenient for others to solve problems.
I am a beginner of fluent. I use "fluent build apk" to apk package. It seems that the default bulid mode is release mode, and the release mode does not define the androidmanifest.xml configuration file, resulting in no "android.permission.INTERNET" permission.
