### ISSUE TITLE
Editor Flashes like it is loading (Android Device)

### ISSUE THREAD

**Issue by asbn223** [tneotia/html-editor-enhanced#205]
Editor flashes from white to grey shown in the screenshot below. 

**Error cause by**
```
E/flutter (20806): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_5)
E/flutter (20806): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (20806): <asynchronous suspension>
E/flutter (20806): #1      InAppWebViewController.evaluateJavascript (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1375:16)
E/flutter (20806): <asynchronous suspension>
E/flutter (20806): #2      _HtmlEditorWidgetMobileState.build.<anonymous closure> (package:html_editor_enhanced/src/widgets/html_editor_widget_mobile.dart:453:23)
E/flutter (20806): <asynchronous suspension>
```

**Code for the HTML Editor**
```
class MultilineEditableTextField extends StatelessWidget {
  MultilineEditableTextField({
    Key? key,
    required this.controller,
    required this.initialText,
    this.hintText,
    this.editorHeight,
  }) : super(key: key);

  final HtmlEditorController controller;
  final String initialText;
  final String? hintText;
  final double? editorHeight;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: editorHeight == null ? 200 : editorHeight,
      width: MediaQuery.of(context).size.width,
      child: HtmlEditor(
        key: UniqueKey(),
        controller: controller,
        htmlEditorOptions: HtmlEditorOptions(
          autoAdjustHeight: false,
          spellCheck: false,
          hint: hintText,
          shouldEnsureVisible: true,
          adjustHeightForKeyboard: true,
          initialText: initialText,
        ),
        htmlToolbarOptions: HtmlToolbarOptions(
          renderSeparatorWidget: true,
          toolbarPosition: ToolbarPosition.custom,
          // toolbarType: ToolbarType.nativeExpandable,
          textStyle: TextStyle(
            fontFamily: 'Poppins',
            fontSize: 12,
            color: Colors.black,
          ),
        ),
        otherOptions: OtherOptions(
          height: editorHeight == null ? 190 : editorHeight!,
          decoration: BoxDecoration(
            color: DraclmsTheme.textFormFieldFillColor,
            border: Border.all(
              color: DraclmsTheme.textFormFieldBorderColor,
              width: 1,
            ),
          ),
        ),
      ),
    );
  }
}
```

**Screenshots**

![269851577_732653491042012_1582409951716138425_n](https://user-images.githubusercontent.com/45443718/149271780-d5696088-1200-48be-8895-afd6c69b764c.jpg)
![270097768_292220416292195_358554537945313358_n](https://user-images.githubusercontent.com/45443718/149271785-e608c8e5-fa02-446a-99f4-f9a5ee6c0d44.jpg)

**Device:**
Android Device Version 11

**Comment by tneotia** [comment]
Did you add internet permission to android manifest?

**Comment by asbn223** [comment]
@tneotia, I have permission for the internet to android manifest.

**Comment by asbn223** [comment]
@tneotia  I am sorry for the inconvenience. I have solve the problem. It was the problem of navigation from flutter. 
**For example:**
```
RaisedButton(
      onPressed: () {
         Navigator.push(context, MaterialPageRoute(builder: (context) => Second()));
      },
      child: Text('Open Second'),
  ),
```
**_You need to change this above code to:_**
```
RaisedButton(
      onPressed: () {
          final page = Second();
          Navigator.push(context,MaterialPageRoute(builder: (context) => page ));
      }, 
      child: Text('Open Second'),
  ),
```
Thank you. Tanay and once again sorry for the inconvenience. I will close this issue with comment.
