### ISSUE TITLE
_HtmlEditorWidgetMobileState Unhandled Exception: setState() called after dispose()

### ISSUE THREAD

**Issue by blue492** [tneotia/html-editor-enhanced#22]
When I call `await controller.getText()` it return the result correct, but it shows these error messages in terminal:

```
E/chromium(16000): [ERROR:aw_browser_terminator.cc(125)] Renderer process (16047) crash detected (code -1).
E/flutter (16000): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: setState() called after dispose(): _HtmlEditorWidgetMobileState#e447c(lifecycle state: defunct, not mounted)
E/flutter (16000): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (16000): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (16000): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (16000): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1231:9)
E/flutter (16000): #1      State.setState (package:flutter/src/widgets/framework.dart:1266:6)
E/flutter (16000): #2      _HtmlEditorWidgetMobileState.resetHeight (package:html_editor_enhanced/src/widgets/html_editor_widget_mobile.dart:89:5)
E/flutter (16000): #3      _HtmlEditorWidgetMobileState.build.<anonymous closure>.<anonymous closure> (package:html_editor_enhanced/src/widgets/html_editor_widget_mobile.dart:465:29)
E/flutter (16000): #4      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (16000): #5      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (16000): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (16000): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (16000): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (16000): #9      _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:386:20)
E/flutter (16000): #10     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:323:15)
E/flutter (16000): #11     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:5)
E/flutter (16000): #12     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter (16000): #13     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:475:11)
E/flutter (16000): #14     _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (16000): #15     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (16000): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (16000): #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (16000): #18     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (16000): #19     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (16000): #20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (16000): #21     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (16000): #22     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (16000): #23     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (16000): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (16000): #25     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (16000): #26     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (16000): #27     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (16000): #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (16000): #29     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (16000): #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (16000): 
E/flutter (16000): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method clearFocus on channel com.pichillilorenzo/flutter_inappwebview_0)
E/flutter (16000): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (16000): <asynchronous suspension>
E/flutter (16000): #1      InAppWebViewController.clearFocus (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1795:12)
E/flutter (16000): <asynchronous suspension>
E/flutter (16000): 
```

Thanks for your work.

**Comment by tneotia** [comment]
Hi, which version of the plugin are you using? And your widget code would be helpful as well. 

It seems you are popping the page after calling `getText()`? This seems related to #11 (which you also posted).

**Comment by tneotia** [comment]
I may have fixed this, please try using 
```yaml
html_editor_enhanced​:
   ​git​:
      ​url​: ​https://github.com/tneotia/html-editor-enhanced.git​
      ​ref​: ​master
```
in pubspec to see if it is fixed. Thanks!

**Comment by axgalache** [comment]
Thank you! I was having the same problem.
I've tried to fetch package from git as you show, but I'm getting error:
Because [app] depends on html_editor_enhanced​ from unknown source "git​", version solving failed.
pub get failed (1; Because [app] depends on html_editor_enhanced​ from unknown source "git​", version solving failed.)

**Comment by tneotia** [comment]
It seems the code I posted had some weird leading and trailing spaces that pubspec didn't like. I edited the code, please try to copy paste again. If you could let me know if the fix works that would be great!

**Comment by tneotia** [comment]
I think I've solved this by just checking `mounted` in the referenced commit. I'm going to close this, it will likely release in v2.0.0 (or you can use git if you need). It won't cause an app crash, just an internal exception.

If you experience this even after v2.0.0 please let me know. Thanks!
