### ISSUE TITLE
error when trying to get data from editor controller [BUG]

### ISSUE THREAD

**Issue by aniketsongara** [tneotia/html-editor-enhanced#224]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method isLoading on channel com.pichillilorenzo/flutter_inappwebview_0)
E/flutter (16119): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (16119): <asynchronous suspension>
E/flutter (16119): #1      InAppWebViewController.isLoading (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1338:12)
E/flutter (16119): <asynchronous suspension>
E/flutter (16119): #2      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:261:39)
E/flutter (16119): <asynchronous suspension>
E/flutter (16119): #3      HtmlEditorController.getText (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:70:16)
E/flutter (16119): <asynchronous suspension>
E/flutter (16119): #4      AddPostController.addPost (package:post_app_v02/controller/add_post_controller.dart:242:15)
E/flutter (16119): <asynchronous suspension>
E/flutter (16119): 
```

**Comment by tneotia** [comment]
Seems like this is a webview related issue - does all other functions work normally? Are you able to see the editor and interact with it?

**Comment by aniketsongara** [comment]
@tneotia everything work fine but when trying to get data from editor controller this error is occurring.

**Comment by asadamatic** [comment]
@aniketsongara Did you find any solution?
I'm getting the same exception when trying to set the editor value using the controller.

`controller.setText()`

**Comment by asadamatic** [comment]
The exception was raised on the ios simulator. It worked on a real android device.
