### ISSUE TITLE
[BUG] i set up  controller.disable() and ToolbarPosition.custom after initialText can't take effect

### ISSUE THREAD

**Issue by boziyoung** [tneotia/html-editor-enhanced#279]
**Describe the bug**
i set up  controller.disable() and ToolbarPosition.custom after the initialText can't take effect

code:
```
 child: HtmlEditor(
                    // 控制器
                    controller: _contentController,
                    htmlEditorOptions: HtmlEditorOptions(
                      autoAdjustHeight: false,
                      hint: "Your Content typr here",
                      shouldEnsureVisible: true,
                      initialText: content,
                    ),

                    htmlToolbarOptions: const HtmlToolbarOptions(
                        toolbarPosition: ToolbarPosition.custom),

              
                    callbacks:
                        Callbacks(onInit: () => _contentController.disable()),
                  ),
```

erro:
```
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:54347/dart_sdk.js:5405:11)
    at Object.nullCheck (http://localhost:54347/dart_sdk.js:5732:30)
    at html_editor_controller_web.HtmlEditorController.new.disable (http://localhost:54347/packages/html_editor_enhanced/src/html_editor_controller_unsupported.dart.lib.js:8349:12)
    at http://localhost:54347/packages/blog_mvapp/src/edit_article.dart.lib.js:1827:1725
    at html_editor_widget_web._HtmlEditorWidgetWebState.new.<anonymous> (http://localhost:54347/packages/html_editor_enhanced/src/html_editor_controller_unsupported.dart.lib.js:8726:77)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:54347/dart_sdk.js:43083:34)
    at Object._async [as async] (http://localhost:54347/dart_sdk.js:43114:7)
    at http://localhost:54347/packages/html_editor_enhanced/src/html_editor_controller_unsupported.dart.lib.js:8720:26
    at Object._checkAndCall (http://localhost:54347/dart_sdk.js:5609:16)
    at Object.dcall (http://localhost:54347/dart_sdk.js:5614:17)
    at HTMLIFrameElement.<anonymous> (http://localhost:54347/dart_sdk.js:115590:21)
```
web show result :
![image](https://user-images.githubusercontent.com/50167927/175956295-cc832c94-bd69-40c5-a2a7-e43ee14a46e7.png)

**Device:**
web 

I've already submitted an question a month ago and I thought it was my fault at the time, but now it looks like it's a bug

**Comment by tneotia** [comment]
initialText should be working normally, no need to use a custom toolbar. Issue I think is because you said custom toolbar, but didnt add the toolbarwidget somewhere else in the widget tree.

**Comment by boziyoung** [comment]
Sorry, yes, this is my fault , it become normally after i add a new the "toolbar widget" in otherwhere
