### ISSUE TITLE
Unhandled Exception: Exception: HTML editor is still loading (JS not working)

### ISSUE THREAD

**Issue by sunnyasr** [tneotia/html-editor-enhanced#384]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Exception: HTML editor is still loading, please wait before evaluating this JS: $('#summernote-2').summernote('focus');!
#0      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:261:9)
#1      HtmlEditorController.setFocus (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:99:5)
#2      EditorController.onReady (package:coope_new/view/single_task/editor/controller/editor_controller.dart:37:30)
#3      DisposableInterface.onInit.<anonymous closure> (package:get/get_state_manager/src/rx_flutter/rx_disposable.dart:21:44)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#7      _invoke (dart:ui/hooks.dart:148:13)
#8      PlatformDispat<…>
flutter: JavaScript execution returned a result of an unsupported type

**Additional context**

**Comment by mariamalbarghouti** [comment]
the same

**Comment by ankeet7x** [comment]
Encountered the same issue.

**Comment by beyzatsc** [comment]
same

**Comment by khize-r** [comment]
I resolved this by adding a 2 sec delay when using controller.setText(). and now I have a new problem. on navigation back 
 [ERROR:aw_browser_terminator.cc(125)] Renderer process (27984) crash detected (code -1).
E/flutter (27785): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method isLoading on channel com.pichillilorenzo/flutter_inappwebview_0)
E/flutter (27785): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (27785): <asynchronous suspension>
E/flutter (27785): #1      InAppWebViewController.isLoading (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1425:12)
E/flutter (27785): <asynchronous suspension>
E/flutter (27785): #2      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:260:39)
E/flutter (27785): <asynchronous suspension>
E/flutter (27785): 
E/flutter (27785): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method isLoading on channel com.pichillilorenzo/flutter_inappwebview_1)
E/flutter (27785): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (27785): <asynchronous suspension>
E/flutter (27785): #1      InAppWebViewController.isLoading (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1425:12)
E/flutter (27785): <asynchronous suspension>
E/flutter (27785): #2      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:260:39)
E/flutter (27785): <asynchronous suspension>
