### ISSUE TITLE
MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_12)[BUG]

### ISSUE THREAD

**Issue by Devandhiran637** [tneotia/html-editor-enhanced#507]
**MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_12)
I/flutter (13435): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
I/flutter (13435): <asynchronous suspension>
I/flutter (13435): #1      InAppWebViewController.evaluateJavascript (package:flutter_inappwebview/src/in_app_webview/in_app_webview_controller.dart:1460:16)
I/flutter (13435): <asynchronous suspension>
I/flutter (13435): #2      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:264:20)
I/flutter (13435): <asynchronous suspension>**

**when i set back button Navigator.of(context).pop() 

this issue replicates**

**
@override
  void dispose() {
    controller.clear();
    controller.clearFocus();

    super.dispose();
  }

 HtmlEditorController controller = HtmlEditorController();

Container(
                            height: 300,
                            child: HtmlEditor(
                              controller: controller, //required
                              otherOptions: OtherOptions(
                                  decoration: BoxDecoration(border: Border())),
                              htmlEditorOptions: HtmlEditorOptions(
                                autoAdjustHeight: true,
                                mobileContextMenu:
                                    ContextMenu(options: ContextMenuOptions()),
                                initialText: messageController.text,
                                hint: "",
                                //initalText: "text content initial, if any",
                              ),
                            ),
                          )

**

**Comment by Aruljebaraj** [comment]
MissingPluginException(No implementation found for method isLoading on channel com.pichillilorenzo/flutter_inappwebview_0) getting is any fixes?

**Comment by RupBarad** [comment]
@tneotia  In android I get this error while press back. 
it show's black view on first screen of html even we back from second screen. 

Error: 
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_3)
E/flutter (24788): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:365:7)
E/flutter (24788): <asynchronous suspension>
E/flutter (24788): #1      AndroidInAppWebViewController.evaluateJavascript (package:flutter_inappwebview_android/src/in_app_webview/in_app_webview_controller.dart:1928:16)
E/flutter (24788): <asynchronous suspension>
E/flutter (24788): #2      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:264:20)
E/flutter (24788): <asynchronous suspension>
E/flutter (24788):

**Comment by Fayis01** [comment]
> MissingPluginException(No implementation found for method isLoading on channel com.pichillilorenzo/flutter_inappwebview_0) getting is any fixes?

are you fixed this ?

**Comment by Aruljebaraj** [comment]
I fixed the issue by adding   flutter_inappwebview: ^6.2.0-beta.2

**Comment by RupBarad** [comment]
I tried this but still get error Unhandled Exception: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_1)

Main problem, For dark theme 
it show's black view on first screen of html editor, even we back from second screen.
