### ISSUE TITLE
Unhandled Exception: Exception: HTML editor is still loading, please wait before evaluating this JS: $('#summernote-2').summernote('code', '');![BUG]

### ISSUE THREAD

**Issue by krishnapada** [tneotia/html-editor-enhanced#527]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Unknown feature SUPPRESS_ERROR_PAGE, null, java.lang.RuntimeException: Unknown feature SUPPRESS_ERROR_PAGE
E/flutter ( 4843): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:649)
E/flutter ( 4843): 	at androidx.webkit.internal.WebViewFeatureInternal.isSupported(WebViewFeatureInternal.java:618)
E/flutter ( 4843): 	at androidx.webkit.WebViewFeature.isFeatureSupported(WebViewFeature.java:611)
E/flutter ( 4843): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.InAppWebView.prepare(InAppWebView.java:436)
E/flutter ( 4843): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.in_app_webview.FlutterWebView.<init>(FlutterWebView.java:82)
E/flutter ( 4843): 	at com.pichillilorenzo.flutter_inappwebview_android.webview.FlutterWebViewFactory.create(FlutterWebViewFactory.java:67)
E/flutter ( 4843): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/flutter ( 4843): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:168)
E/flutter ( 4843): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter ( 4843): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter ( 4843): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/flutter ( 4843): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/flutter ( 4843): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 4843): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 4843): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter ( 4843): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 4843): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter ( 4843): 	at android.os.Looper.loop(Looper.java:288)
E/flutter ( 4843): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter ( 4843): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 4843): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter ( 4843): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter ( 4843): )
E/flutter ( 4843): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 4843): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 4843): <asynchronous suspension>

**Comment by Siddharth2212** [comment]
Facing same issue after update to latest 2.6.0

**Comment by YudizAndroidKishan** [comment]
facing same issue

**Comment by AmmarTN** [comment]
any update?

**Comment by krishnapada** [comment]
any update

**Comment by decisionslab2** [comment]
facing same issue

**Comment by Mehedi50200** [comment]
same issue...

**Comment by webdevonline** [comment]
Has there been any progress on this bug? I am having the same issue, and it's been three months since it was reported.

**Comment by krishnapada** [comment]
Yes, I am working on it. do this. flutter clean
flutter pub cache clean
flutter pub get

**Comment by webdevonline** [comment]
> Yes, I am working on it. do this. flutter clean flutter pub cache clean flutter pub get
> […](#)

I had done that already and the error is still happening. It doesn't happen every time. I am running on an emulator. But it happens more often than not. It happens when I make the following call:
 htmlController.insertHtml('<img src="${theFile.full_path}" alt="${theFile.file_type}" />');

**Comment by webdevonline** [comment]
Has there been any update to this?

**Comment by jawad111** [comment]
> Has there been any progress on this bug? I am having the same issue, and it's been three months since it was reported. The "bug fix" mentioned in the jawad111 reply does not work. It just creates new errors saying that the wrong field is being sent by html_editor.
> 
> Here's the error I am getting: E/flutter (14267): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: HTML editor is still loading, please wait before evaluating this JS: $('#summernote-2').summernote('pasteHTML', '<img src="[https://storage.googleapis.com/g-green-backend-bucket-1/bluetwotest%2FClover_small.jpg\](https://storage.googleapis.com/g-green-backend-bucket-1/bluetwotest%2FClover_small.jpg%5C)" alt="image/jpeg" />');!

can you share your log please?

**Comment by IlonaBondarovich** [comment]
Apparently the problem is in the flutter_inappwebview package. On certain versions flutter_inappwebview produces the same error on Android. html_editor_enhanced package 2.6.0 uses flutter_inappwebview 6.0.0, there is probably some kind of bug in 6.0.0 version, because in flutter_inappwebview 5.7.2+3 there is no such problem
